name: Backtest

on:
  pull_request:
    paths:
      - 'user_data/**'
      - 'docker-compose.yml'
  push:
    branches: [ main ]
    paths:
      - 'user_data/**'
      - 'docker-compose.yml'

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare data dir
        run: |
          mkdir -p user_data/data/binance
          # Add your own cached candles here if you keep them; otherwise freqtrade can dl via dl-data.

      - name: Pull Freqtrade image
        run: docker pull freqtradeorg/freqtrade:stable

      - name: Download sample data (quick)
        run: |
          docker run --rm -v ${{ github.workspace }}/user_data:/freqtrade/user_data \
            freqtradeorg/freqtrade:stable \
            download-data -t 5m --timerange 20250101- --exchange binance \
            --pairs BTC/USDT,ETH/USDT

      - name: Run backtest
        run: |
          docker run --rm -v ${{ github.workspace }}/user_data:/freqtrade/user_data \
            freqtradeorg/freqtrade:stable \
            backtesting --config /freqtrade/user_data/config.json \
            --strategy SampleStrategy \
            --timeframe 5m \
            --timerange 20250110-20250120 \
            --export trades \
            --export-filename /freqtrade/user_data/backtest_results/sample_bt.json

      - name: Upload backtest results
        uses: actions/upload-artifact@v4
        with:
          name: backtest-results
          path: user_data/backtest_results/
          
