name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]
    paths:
      - 'user_data/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch: {}   # 👈 enables manual runs
